create table if not exists public.post_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  en_word text not null,
  es_word text not null,
  ca_word text not null,
  caption text not null,
  image_url text,
  instagram_media_id text,
  status text not null,
  error_message text
);

alter table public.post_logs enable row level security;

drop policy if exists post_logs_select on public.post_logs;
drop policy if exists post_logs_insert on public.post_logs;

create policy post_logs_select
  on public.post_logs
  for select
  to anon
  using (true);

create policy post_logs_insert
  on public.post_logs
  for insert
  to anon
  with check (true);
